{% set name = "flask-restx" %}
{% set version = "1.1.0" %}
{% set sha256 = "62b6b6c9de65e5960cf4f8b35e1bd3eca6998838a01b2f71e2a9d4c14a4ccd14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aniso8601 >=0.82
    - jsonschema
    - Flask >=0.8
    - werkzeug
    - pytz
    - six >=1.3.0

test:
  imports:
    - flask_restx

about:
  home: https://github.com/python-restx/flask-restx/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fully featured framework for fast, easy and documented API development with Flask

  description: |
    Flask-RESTX is an extension for Flask that adds support for quickly building REST APIs.
    Flask-RESTX encourages best practices with minimal setup. If you are familiar with Flask,
    Flask-RESTX should be easy to pick up. It provides a coherent collection of decorators and
    tools to describe your API and expose its documentation properly using Swagger.
  doc_url: https://flask-restx.readthedocs.io/
  dev_url: https://github.com/python-restx/flask-restx/

extra:
  recipe-maintainers:
    - SVilgelm
    - fhoehle
