{% set name = "flask-restx" %}
{% set version = "1.3.0" %}
{% set sha256 = "4f3d3fa7b6191fcc715b18c201a12cd875176f92ba4acc61626ccfd571ee1728" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aniso8601 >=0.82
    - jsonschema
    - Flask >=0.8,!=2.0.0
    - werkzeug !=2.0.0
    - pytz
    - importlib-resources

test:
  imports:
    - flask_restx
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip    

about:
  home: https://github.com/python-restx/flask-restx/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fully featured framework for fast, easy and documented API development with Flask

  description: |
    Flask-RESTX is an extension for Flask that adds support for quickly building REST APIs.
    Flask-RESTX encourages best practices with minimal setup. If you are familiar with Flask,
    Flask-RESTX should be easy to pick up. It provides a coherent collection of decorators and
    tools to describe your API and expose its documentation properly using Swagger.
  doc_url: https://flask-restx.readthedocs.io/
  dev_url: https://github.com/python-restx/flask-restx/

extra:
  recipe-maintainers:
    - SVilgelm
    - fhoehle
